# Generated by Django 4.2.5 on 2023-09-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('File_up', '0002_alter_file_options_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=250, upload_to='uploads/'),
        ),
    ]
